### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by zzpzbl** [Xiejiadong/ECNU_Undergraduate_Dissertation_Template#2]
一个是目录要换成理科类的，1，2，3这种而不是一，二，三
二是文章最上面缺少标题，如图
![image](https://user-images.githubusercontent.com/51434091/155868480-77b943d7-fb8d-4921-a5f2-779c274e7c90.png)

**Comment by zzpzbl** [comment]
![image](https://user-images.githubusercontent.com/51434091/155868496-ee209d0a-269d-46eb-a11b-02d2929548e1.png)
现在是空的

**Comment by Tsyxxxka** [comment]
Fixed.
